name: mem Specification
description: Create a new specification for mem
title: "[Spec]: "
labels: ["mem-spec"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the specification details below.
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: High-level summary of the specification.
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: What are the primary goals of this feature?
    validations:
      required: true
  - type: textarea
    id: technical-approach
    attributes:
      label: Technical Approach
      description: How will this be implemented?
    validations:
      required: true
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: List the criteria for success.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Additional context or references.
    validations:
      required: false
